version: "3.9"

services:
  go-app:
    container_name: go-app
    image: shivangshandilya/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_SERVICE_NAME: "akola-go-oTel-collector"
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: DELTA
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=abcd12345
      OTEL_LOGS_EXPORTER: otlp
    ports:
      - "8000:8000"
    links:
      - otel-collector
    depends_on:
      - go_db
      - otel-collector

  go_db:
    container_name: go-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

  otel-collector:
    build:
      dockerfile: DockerNrdot
    command: ["--config=/etc/collector-config.yaml"]
    environment:
      - NEW_RELIC_OTLP_ENDPOINT
      - NEW_RELIC_API_KEY
    volumes:
      - ./collector-config.yaml:/etc/collector-config.yaml
    ports:
      - "4317:4317"

volumes:
  pgdata: {}
